### ISSUE TITLE
Header.scss header class has duplicate property

### ISSUE THREAD

**Issue by topalavlad** [fullstackopen-2019/fullstackopen-2019.github.io#163]
`transition` is defined twice in `Header.scss`. I'm guessing the second one should stay since it was overwriting the first one anyway.

```scss
.header {
  ...
  transition: top 0.2s ease-in-out;
  ...
  transition: all 0.2s ease-in-out;
}
```
